### ISSUE TITLE
Using Default database all the time

### ISSUE THREAD

**Issue by DarthShoge** [oste/rds-migrate#1]
The code does not select the database in the db params. thus all commands are ran against the default database.
see https://github.com/oste/rds-migrate/blob/c99c5745b8b358d50acea3bb75024b4bff2820e4/index.js#L14-L17
 The following rds params would fix this problem: 
const params = {
  resourceArn: process.env.RDS_RESOURCE_ARN,
  secretArn: process.env.RDS_SECRET_ARN,
  **database: process.env.RDS_DATABASE,**
};

**Comment by oste** [comment]
Thanks for posting @DarthShoge and sorry for the delay. I recently rewrote this library and I took your suggestion. Please give the latest version 1 a try.
